
CREATE TABLE Company
(
  ID      VARCHAR(200) NOT NULL COMMENT '아이디',
  NAME    VARCHAR(200) NOT NULL COMMENT '이름',
  AGE     INT          NULL     COMMENT '나이',
  ADDRESS VARCHAR(200) NULL     COMMENT '주소',
  SALARY  INT          NOT NULL COMMENT '월급',
  PRIMARY KEY (ID)
) COMMENT '회사';

CREATE TABLE Company_DEPT
(
  Company_ID VARCHAR(200) NOT NULL COMMENT '아이디',
  DEPT_ID    VARCHAR(200) NOT NULL COMMENT 'uniqueID'
) COMMENT '관계 테이블';

CREATE TABLE DEPARTMENT
(
  ID   VARCHAR(200) NOT NULL COMMENT 'uniqueID',
  DEPT VARCHAR(200) NOT NULL COMMENT '부서',
  PRIMARY KEY (ID)
) COMMENT '부서 공통';

ALTER TABLE Company_DEPT
  ADD CONSTRAINT FK_Company_TO_Company_DEPT
    FOREIGN KEY (Company_ID)
    REFERENCES Company (ID);

ALTER TABLE Company_DEPT
  ADD CONSTRAINT FK_DEPARTMENT_TO_Company_DEPT
    FOREIGN KEY (DEPT_ID)
    REFERENCES DEPARTMENT (ID);
